# Generated by Django 5.1.6 on 2025-04-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='contractor_invoice',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='project_title',
            new_name='contractor_invoice_project_number',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='end_date',
            new_name='job_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='haul_rate_type',
            new_name='prevailing_or_not',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='end_time',
            new_name='shift_start',
        ),
        migrations.RemoveField(
            model_name='job',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='job',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='job',
            name='haul_rate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='rate_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='job',
            name='truck_type',
        ),
        migrations.AddField(
            model_name='job',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_backhaul_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_foreman_contact',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_foreman_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='new_contractor_invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='new_contractor_invoice_project_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prime_contractor',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='prime_contractor_project_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='report_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sap_or_sp_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='truck_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='backhaul_loading_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backhaul_loading_jobs', to='myapp.address'),
        ),
        migrations.AddField(
            model_name='job',
            name='backhaul_unloading_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backhaul_unloading_jobs', to='myapp.address'),
        ),
        migrations.AlterField(
            model_name='job',
            name='loading_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_jobs', to='myapp.address'),
        ),
        migrations.AlterField(
            model_name='job',
            name='unloading_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unloading_jobs', to='myapp.address'),
        ),
    ]
