# Generated by Django 5.1.6 on 2025-04-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_address_rename_job_title_job_contractor_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='prevailing_wage_class_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
