# Generated by Django 5.1.6 on 2025-04-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_job_prevailing_wage_class_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('driver_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='myapp.drivertruckassignment')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='myapp.job')),
            ],
            options={
                'unique_together': {('job', 'driver_truck')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='driver_truck_assignments',
            field=models.ManyToManyField(related_name='jobs', through='myapp.JobDriverAssignment', to='myapp.drivertruckassignment'),
        ),
    ]
