# Generated by Django 5.1.6 on 2025-10-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_invoice_invoiceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_start', models.DateField(db_column='week_start')),
                ('week_end', models.DateField(db_column='week_end')),
                ('total_weight_or_hours', models.DecimalField(db_column='total_weight_or_hours', decimal_places=2, max_digits=14)),
                ('total_truck_paid', models.DecimalField(db_column='total_truck_paid', decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=14)),
                ('total_due', models.DecimalField(db_column='total_due', decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_reports', to='myapp.driver')),
            ],
            options={
                'db_table': 'myapp_payreport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayReportLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('job_number', models.CharField(db_column='job_number', max_length=255)),
                ('truck_number', models.CharField(db_column='truck_number', max_length=100)),
                ('trailer_number', models.CharField(db_column='trailer_number', max_length=100)),
                ('loaded', models.CharField(db_column='loaded', max_length=255)),
                ('unloaded', models.CharField(db_column='unloaded', max_length=255)),
                ('weight_or_hour', models.DecimalField(db_column='weight_or_hour', decimal_places=2, max_digits=12)),
                ('truck_paid', models.DecimalField(db_column='truck_paid', decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=14)),
                ('trailer_rent', models.DecimalField(db_column='trailer_rent', decimal_places=2, max_digits=14)),
                ('broker_charge', models.DecimalField(db_column='broker_charge', decimal_places=2, max_digits=14)),
                ('contractor_paid', models.DecimalField(db_column='contractor_paid', decimal_places=2, max_digits=14)),
                ('fuel_program', models.DecimalField(db_column='fuel_program', decimal_places=2, max_digits=12)),
                ('fuel_pilot_or_kt', models.DecimalField(db_column='fuel_pilot_or_kt', decimal_places=2, max_digits=12)),
                ('fuel_surcharge', models.DecimalField(db_column='fuel_surcharge', decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_lines', to='myapp.job')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='myapp.payreport')),
            ],
            options={
                'db_table': 'myapp_payreportline',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='payreport',
            constraint=models.CheckConstraint(condition=models.Q(('week_end__gte', models.F('week_start'))), name='pr_week_start_lte_end'),
        ),
        migrations.AlterUniqueTogether(
            name='payreport',
            unique_together={('driver', 'week_start', 'week_end')},
        ),
        migrations.AddIndex(
            model_name='payreportline',
            index=models.Index(fields=['report', 'date'], name='myapp_payre_report__367a71_idx'),
        ),
        migrations.AddIndex(
            model_name='payreportline',
            index=models.Index(fields=['job_number'], name='myapp_payre_job_num_ec6ee4_idx'),
        ),
    ]
