# Generated by Django 5.1.6 on 2025-10-31 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payreport_payreportline_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='payreportline',
            name='fuel_pilot_or_kt',
        ),
        migrations.RemoveField(
            model_name='payreportline',
            name='fuel_program',
        ),
        migrations.RemoveField(
            model_name='payreportline',
            name='fuel_surcharge',
        ),
        migrations.AddField(
            model_name='payreport',
            name='fuel_pilot_or_kt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payreport',
            name='fuel_program',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payreport',
            name='fuel_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='payreport',
            name='total_amount',
            field=models.DecimalField(db_column='total_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreport',
            name='total_due',
            field=models.DecimalField(db_column='total_due', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreport',
            name='total_truck_paid',
            field=models.DecimalField(db_column='total_truck_paid', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreport',
            name='total_weight_or_hours',
            field=models.DecimalField(db_column='total_weight_or_hours', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='payreportline',
            name='broker_charge',
            field=models.DecimalField(db_column='broker_charge', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreportline',
            name='contractor_paid',
            field=models.DecimalField(db_column='contractor_paid', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreportline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='payreportline',
            name='total',
            field=models.DecimalField(db_column='total', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreportline',
            name='trailer_rent',
            field=models.DecimalField(db_column='trailer_rent', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreportline',
            name='truck_paid',
            field=models.DecimalField(db_column='truck_paid', decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payreportline',
            name='weight_or_hour',
            field=models.DecimalField(db_column='weight_or_hour', decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='payreport',
            index=models.Index(fields=['driver', 'week_start', 'week_end'], name='pr_driver_week_idx'),
        ),
    ]
