# Generated by Django 5.1.6 on 2025-10-31 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_payreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='prime_contractor_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_as_prime', to='myapp.customer'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['prime_contractor_customer'], name='myapp_job_prime_c_ff467b_idx'),
        ),
    ]
