# Generated by Django 5.1.6 on 2025-11-12 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_job_prime_contractor_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('salt', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('purpose', models.CharField(default='password_reset', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='end_date',
            field=models.DateField(blank=True, help_text='End of the invoice period (week range)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start of the invoice period (week range)', null=True),
        ),
        migrations.AddConstraint(
            model_name='payreport',
            constraint=models.UniqueConstraint(fields=('driver', 'week_start', 'week_end'), name='uniq_payreport_driver_week'),
        ),
        migrations.AddField(
            model_name='passwordotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordotp',
            index=models.Index(fields=['user', 'created_at'], name='myapp_passw_user_id_b46287_idx'),
        ),
    ]
