# Generated by Django 5.1.6 on 2025-11-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_job_prime_contractor_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='plate_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
