# Generated by Django 5.1.6 on 2025-12-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_driver_license_expiry_date_driver_license_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='medical_card_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
