# Generated by Django 5.1.6 on 2026-02-17 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_repair_after_fake_0009"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="submitted_by_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_invoices",
                to="myapp.driver",
            ),
        ),
    ]
