# Generated by Django 5.1.6 on 2026-02-18 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_invoice_submitted_by_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
