# Generated by Django 5.2.11 on 2026-03-17 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdriverassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdriverassignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdriverassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('en_route', 'En Route'), ('on_site', 'On Site'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
        migrations.CreateModel(
            name='JobIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('equipment', 'Equipment Problem'), ('safety', 'Safety Concern'), ('access', 'Site Access Issue'), ('material', 'Material Problem'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='myapp.driver')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='myapp.job')),
            ],
        ),
    ]
