# Generated by Django 5.2.11 on 2026-03-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_jobdriverassignment_completed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobIssue',
        ),
    ]
