# Generated by Django 6.0.1 on 2026-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdriverassignment',
            name='on_site_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
