"""
Django settings for backend_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import django
from dotenv import load_dotenv
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3#(cahk+@7w0!d$!b94+7^$s=fei+2!z*$-9^&s^@j15xfxphy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*' ]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'rest_framework_simplejwt',
    'myapp',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



# Load environment variables (prefer repo root .env, then local)
load_dotenv(BASE_DIR.parent.parent / ".env")
load_dotenv(BASE_DIR.parent / ".env")




DATABASES = {
  "default": dj_database_url.config(
    env="DATABASE_URL",
    conn_max_age=600,
    ssl_require=os.environ.get("DATABASE_SSL_REQUIRE", "false").lower() == "true"
  )
}






# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",   # Angular web app (Development)
    "http://localhost:8081",   # React Native Expo mobile app (Development)
    "https://yourdomain.com",  # Production (Replace with actual domain)
]
CORS_ALLOW_ALL_ORIGINS = False
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
# }
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Allow public access by default
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # 1-day token expiry
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 7-day refresh token expiry
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
}
# AUTH_USER_MODEL = "myapp.User"

# SMTP2GO Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("SMTP_HOST", "mail.smtp2go.com")
# SMTP2GO works on 2525/587; default to 587 to avoid timeouts on some hosts, allow override
EMAIL_PORT = int(os.environ.get("SMTP_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # keep SSL off; use TLS on 587/2525

# Credentials from .env file (support a few env names to avoid misconfig)
EMAIL_HOST_USER = (
    os.environ.get("SMTP_USERNAME")
    or os.environ.get("SMTP_USER")
    or os.environ.get("SMTP2GO_USERNAME")
    or os.environ.get("EMAIL_HOST_USER")
    or ""
)
EMAIL_HOST_PASSWORD = (
    os.environ.get("SMTP_PASSWORD")
    or os.environ.get("SMTP_PASS")
    or os.environ.get("SMTP2GO_PASSWORD")
    or os.environ.get("EMAIL_HOST_PASSWORD")
    or ""
)
DEFAULT_FROM_EMAIL = os.environ.get("FROM_EMAIL") or EMAIL_HOST_USER or "no-reply@example.com"

# Email timeout settings
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", 20))  # seconds

SPECTACULAR_SETTINGS = {
    'TITLE': 'Eaton LLC API',
    'DESCRIPTION': 'API documentation for Eaton LLC mobile/backend integration',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
